version: '3'

services:
  app:
    build: .
    entrypoint: dockerize --wait tcp://db:5432 -timeout 120s
    command: yarn start:dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    networks:
      - app-network
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
    networks:
      - app-network
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/costaweb.dev.br/fullchain.pem:/etc/nginx/certificates/fullchain.pem
      - /etc/letsencrypt/live/costaweb.dev.br/privkey.pem:/etc/nginx/certificates/privkey.pem
    networks:
      - app-network
    depends_on:
      - app
  in_memory:
    image: redis
    restart: always
    env_file:
      - .env
    command: redis-server --requirepass ${PASS} --maxmemory 3gb --maxmemory-policy allkeys-lru
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
networks:
  app-network:
