version: '3'

services:
  app:
    build: .
    entrypoint: dockerize --wait tcp://db:5432 -timeout 120s
    command: yarn start:dev
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    networks:
      - app-network
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - database
    networks:
      - app-network
  nginx:
    image: nginx
    ports:
      - "80:80"
    restart: always
    env_file:
      - .env
    command: redis-server --requirepass ${PASS} --maxmemory 3gb --maxmemory-policy allkeys-lru
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.dev.conf:ro
    networks:
      - app-network
    depends_on:
      - app
  in_memory:
    image: redis
    command: redis-server --requirepass admin
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
volumes:
  database:
networks:
  app-network: