name: Run all tests 

on: [push]

jobs:
  run-unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - run: yarn
      - run: yarn test:workflow
  
  run-machine-prod:
    name: Run Ec2 Prod
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: appleboy/ssh-action@master
        with:
          host: ec2-54-145-251-235.compute-1.amazonaws.com
          username: admin
          key: NEXLY_EC2.pem 
          port: 22
          script:
            ssh  -o StrictHostKeyChecking=no -i "NEXLY_EC2.pem" -p 22 admin@ec2-54-145-251-235.compute-1.amazonaws.com "ls"
