name: Run all tests 

on: [push]

jobs:
  run-unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - run: yarn
      - run: yarn test:workflow
  
  run-machine-prod:
    name: Run Ec2 Prod
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - run: chmod 400 NEXLY_EC2.pem
      - run: ssh -T -i "NEXLY_EC2.pem" -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null admin@ec2-54-145-251-235.compute-1.amazonaws.com "sudo su && cd nexly-members && git config --global --add safe.directory /home/admin/nexly-members && git pull origin main && exit && exit"
